In [ ]:
# RTFD/numpy-html-1.15.1/reference/routines.linalg.html

In [1]:
import numpy as np
from numpy import linalg as LA
import pprint

# 矩阵和向量积 - P.650

In [14]:
A = np.arange(9).reshape(3,3)
B = np.arange(12).reshape(3,4)

pprint.pprint(A)
pprint.pprint(B)

pprint.pprint(A.dot(B))        # 数组点积
pprint.pprint(np.dot(A, B))
pprint.pprint(np.matmul(A, B)) # 矩阵积


a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
pprint.pprint(np.vdot(a,b))  # 向量点积
pprint.pprint(np.inner(a,b)) # 向量内积
pprint.pprint(np.outer(a,b)) # 向量外积


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
130
130
array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20],
       [18, 21, 24, 27, 30],
       [24, 28, 32, 36, 40],
       [30, 35, 40, 45, 50]])


# 分解 - P.667


In [16]:
A = np.arange(16).reshape(4,4)
q, r = LA.qr(A, mode='complete')
pprint.pprint(q)
pprint.pprint(r)
np.allclose(A, np.dot(q,r))

array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
       [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
       [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
       [-0.80178373,  0.23904572,  0.12966702,  0.53215267]])
array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
        -1.97773319e+01],
       [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
        -3.58568583e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
        -5.12511879e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -8.82043219e-16]])


True

# 特征值 - P.672


In [23]:
A = np.diag((1, 2, 3))
w, v = LA.eig(A)
pprint.pprint(w) # 特征值
pprint.pprint(v) # 特征向量
pprint.pprint(A @ v[0])
pprint.pprint(w[0] * v[0])
np.allclose(A @ v[0], w[0] * v[0])

array([1., 2., 3.])
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
array([1., 0., 0.])
array([1., 0., 0.])


True

# 范式 - P.678


# 方程求解和矩阵逆 - P.685


In [8]:
# FIXME(zhoujiagen) restart here 20181019
# file:///Users/zhoujiagen/Google%20Drive/RTFD/numpy-html-1.15.1/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv
A = np.arange(16).reshape(4,4)
Ainv = LA.inv(A)
pprint.pprint(np.dot(A, Ainv))
np.allclose(A @ Ainv, np.eye(4))

array([[ 1.5   , -1.    ,  0.5   , -0.1875],
       [ 0.    ,  0.    ,  0.5   ,  0.    ],
       [ 0.    ,  0.    , -0.5   ,  0.    ],
       [ 0.    ,  8.    , -2.5   ,  4.    ]])


False

# 异常 - P.691


# 多个矩阵上的线性代数 - P.692